define mc = DynamicCharacter("name", color="#ffaf05")

define js = Character("Josy", color="#ff1c63")
define my = Character("Maya", color = "#a7f442")
define sa = Character("Sage", color = "#BCB88A")
define isa = Character("Isabella", color="#d8f2ff")
define ice = Character("The Ice Queen", color="#d8f2ff")
define qu = Character("Quinn", color="#a0abff")
define ca = Character("Cathy", color="#ff3d0c")
define cam = Character("Camila", color="#c55ffc")
define ri = Character("Riona", color="#6b6461")
define ja = Character("Jade", color="#357d1c")
define ji = Character("Jill", color="#ffe9b9")

define bu = Character("Professor Burke", color="bc9360")
define sb = Character("Stephen", color="bc9360")

define tm = Character("Tommy", color="#9e5900")
define rs = Character("Rusty", color="#ff5630")
define jac = Character("Jacob", color="#dba42e")
define jm = Character("Jamie", color="#f4e842")
define le = Character("Leon", color="#c16000")
define ni = Character("Nick", color="#ffc023")
define jb = Character("John Boy", color="#fced1b")

define an = Character("Anthony", color="#5623ff")
define ch = Character("Chad", color="#23b4fc")
define dw = Character("Dawe", color= "#45ebf7")

define mg = Character("Magnar", color="#c700dd")
define sy = Character("Sally", color="#d450d8")
define rn = Character("Ron", color="#683b89")
define eu = Character("Eugene", color="#620251")
define tri = Character("Tri-betas", color="#d450d8")

define ty = Character("Tybalt", color="#87fa5a")
define rich = Character("Rich", color="#83f97c")
define tr = Character("Trent", color="#229c67")
define lu = Character("Lucas", color="#289460")
define go = Character("Gordon", color="#03a329")

define ml = Character("Melanie", color="#ff99cc")
define sar = Character("Sarah", color="#ee134a")
define el = Character("Elena", color="#a333a5")
define mn = Character("Mona", color="#a333a5")
define ar = Character("Arieth", color="#FF906A")
define he = Character("Heather", color="#f7dfc8")


define beth = Character("Beth", color="a9f2b4")
define bo = Character("Bouncer", color="#ff0000")
define stan = Character("Stanley", color="#ff0000")
define de = Character("Derek", color="#0066ff")
define dn = Character("Dany", color="#ab54f7")
define dpc = Character("Dr PinkCake", color="#ff7ffa")
define dad = Character("Neil", color= "#0cf977")
define dad2 = Character("Dad", color= "#0cf977")
define troy = Character("Troy", color="#ff0000")
define st = Character("Steve", color="#f7dfc8")
define kid = Character("Kid")
define wen = Character("Wendy", color="#c613c3")
define mi = Character("Minny", color="#b723a5")
define mon = Character("Monica", color="#ab54f7")
define pt = Character("Pete", color="#42eef4")
define tn = Character("Tina", color="#42eef4")


define ash = Character("Ashley", color="#42eef4")
define en = Character("Envy", color="#42f450")
define ro = Character("Rose", color="#d11b42")
define ly = Character("Lily", color="#d749ff")
define br = Character("Brandi", color="#76fcd1")
define sn = Character("Sandy", color="#b7a07b")

define girl = Character("Girl", color="a9f2b4")
define be = Character("Bert", color="#f7dfc8")
define hg = Character("HOT girl", color ="#ce588f")
define bt = Character("Bartender", color ="#a9f2b4")
define rc = Character("Receptionist", color="a9f2b4")
define ll = Character("Cafeteria worker", color="a9f2b4")
define uk = Character("Unknown", color="#f7dfc8")
define jc = Character("Jock", color="#5623ff")
define jcs = Character("Jocks", color="#5623ff")
define dikc = Character("DIK", color="#ffc666")
define dikcs = Character("DIKs", color="#ffc666")
define cl = Character("Clerk", color="#f7dfc8")
define bs = Character("Boss", color="#f7dfc8")
define cs = Character("Customer", color="#f7dfc8")
define cs2 = Character("Old lady", color="#f7dfc8")
define sec = Character("Security", color="#f7dfc8")
define stu = Character("Student", color="#ec5c5c")
define fem = Character("Feminist", color="#c613c3")
define prep = Character("Prep", color="#76f422")
define prepp = Character("Prep pledger", color="#76f422")
define maid = Character("Maid")
define wife = Character("Wife")
define husband = Character("Husband")
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
